package constants

const (
	GenderFlag               = "gender"
	AgeFlag                  = "age"
	SmokingFlag              = "smoking"
	YellowFingersFlag        = "yellow-fingers"
	AnxietyFlag              = "anxiety"
	PeerPressureFlag         = "peer-pressure"
	ChronicDisease           = "chronic-disease"
	FatigueFlag              = "fatigue"
	AllergyFlag              = "allergy"
	WheezingFlag             = "wheezing"
	AlcoholConsumingFlag     = "alcohol-consuming"
	CoughingFlag             = "coughing"
	ShortnessOfBreathFlag    = "shortness-of-breath"
	SwallowingDifficultyFlag = "swallowing-difficulty"
	ChestPainFlag            = "chest-pain"
	LungCancerFlag           = "lung-cancer"
	PredictResultCommand     = "predict-result"

	GenderFlagShort               = "g"
	AgeFlagShort                  = "a"
	SmokingFlagShort              = "s"
	YellowFingersFlagShort        = "y"
	AnxietyFlagShort              = "x"
	PeerPressureFlagShort         = "p"
	ChronicDiseaseFlagShort       = "c"
	FatigueFlagShort              = "f"
	AllergyFlagShort              = "l"
	WheezingFlagShort             = "w"
	AlcoholConsumingFlagShort     = "o"
	CoughingFlagShort             = "i"
	ShortnessOfBreathFlagShort    = "b"
	SwallowingDifficultyFlagShort = "d"
	ChestPainFlagShort            = "k"
	LungCancerFlagShort           = "m"

	BaseUrl         = "http://127.0.0.1:5000"
	ApplicationJson = "application/json"
)
